server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # LA LÍNEA MÁGICA: Si no encuentra el archivo o carpeta, redirige a /index.html
        try_files $uri $uri/ /index.html;
    }

    # Caché para archivos estáticos (opcional pero recomendado)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires max;
        log_not_found off;
    }
}