CREATE DATABASE DB_HORWORKS;
USE DB_HORWORKS;

CREATE TABLE HOR_Usuario(
	USU_Id				INT				AUTO_INCREMENT,
    USU_Nombre			NVARCHAR(30)	NOT NULL,
    USU_Usuario			NVARCHAR(30)	NOT NULL,
    USU_Correo			NVARCHAR(80)	NOT NULL,
    USU_Contrasenia		NVARCHAR(80)	NOT NULL,
    USU_Foto			NVARCHAR(255),
    USU_Estado			BOOL			NOT NULL	DEFAULT 1,
    USU_Tickets			INT(1),
    
    PRIMARY KEY(USU_Id)
);

CREATE TABLE HOR_Equipo(
	EQU_Id			INT		 		AUTO_INCREMENT,
    EQU_Nombre		NVARCHAR(40)	NOT NULL,
    EQU_Foto		NVARCHAR(255),
    EQU_Auditor		INT				NOT NULL,
    
    PRIMARY KEY(EQU_Id)
);

CREATE TABLE HOR_Grupos(
	USU_Id			INT,
    EQU_Id			INT,
    
    FOREIGN KEY(USU_Id) REFERENCES HOR_Usuario(USU_Id),
    FOREIGN KEY(EQU_Id) REFERENCES HOR_Equipo(EQU_Id)
);